laPlan = {
    'city': 'Los Angeles', 
    'tour': 
    [
        [
            {
                'travel_time': 0,
                'rating': '4.7',
                'name': 'STAPLES Center',
                'time_to_show': '9 : 00 am to 10 : 00 am',
                'time_spent': 1,
                'place_id': 'ChIJkyrqXbjHwoAR1bJ76zx89B8',
                'travel_dist': 0,
                'no_of_ratings': 9615,
                'images': ['img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/1.jpeg', 'img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/2.jpeg', 'img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/3.jpeg', 'img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/4.jpeg'],
                'cost': 10,
                'time': 0,
                'lat': 34.04,
                'lng': -118.27,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 10,
                'rating': '4.5',
                'name': 'El Pueblo de Los Angeles Historical Monument',
                'time_to_show': '10 : 10 am to 11 : 40 am',
                'place_id': 'ChIJgQpEAUXGwoARoG9LzK0GhV0',
                'time_spent': 1.5,
                'travel_dist': 5.202,
                'no_of_ratings': 957,
                'images': ['img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/1.jpeg', 'img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/2.jpeg', 'img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/3.jpeg', 'img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/4.jpeg'],
                'cost': 10,
                'time': '1.166666666666666657414808128',
                'lat': 34.06,
                'lng': -118.24,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 5,
                'rating': '4.6',
                'name': 'The Broad',
                'time_to_show': '11 : 45 am to 12 : 45 pm',
                'place_id': 'ChIJXaYsEk3GwoARvx7RKBUE8Zg',
                'time_spent': 1,
                'travel_dist': 1.637,
                'no_of_ratings': 4088,
                'images': ['img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/1.jpeg', 'img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/2.jpeg', 'img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/3.jpeg', 'img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/4.jpeg'],
                'cost': 10,
                'time': '2.749999999999999986122212192',
                'lat': 34.05,
                'lng': -118.25,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 10,
                'rating': '4.7',
                'name': 'Natural History Museum of Los Angeles County',
                'time_to_show': '12 : 55 pm to 3 : 55 pm',
                'place_id': 'ChIJXzARBf3HwoARJyT7uZSV-G4',
                'time_spent': 3,
                'travel_dist': 6.972,
                'no_of_ratings': 3171,
                'images': ['img/data/Los Angeles/sites/ChIJXzARBf3HwoARJyT7uZSV-G4/1.jpeg', 'img/data/Los Angeles/sites/ChIJXzARBf3HwoARJyT7uZSV-G4/2.jpeg', 'img/data/Los Angeles/sites/ChIJXzARBf3HwoARJyT7uZSV-G4/3.jpeg', 'img/data/Los Angeles/sites/ChIJXzARBf3HwoARJyT7uZSV-G4/4.jpeg'],
                'cost': 10,
                'time': '3.916666666666666643537020320',
                'lat': 34.02,
                'lng': -118.29,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 14,
                'rating': '4.7',
                'name': 'Walt Disney Concert Hall',
                'time_to_show': '4 : 08 pm to 5 : 09 pm',
                'place_id': 'ChIJ0xG7n03GwoARsDH_OyyMcrM',
                'time_spent': 1,
                'travel_dist': 7.416,
                'no_of_ratings': 3284,
                'images': ['img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/1.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/2.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/3.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/4.jpeg'],
                'cost': 10,
                'time': '7.149999999999999980571097069',
                'lat': 34.06,
                'lng': -118.25,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
                {
                'travel_time': 11,
                'rating': '4.7',
                'name': 'California Science Center',
                'time_to_show': '5 : 20 pm to 7 : 50 pm',
                'time_spent': 1.5,
                'place_id': 'ChIJ21yHTgjIwoARcrUbrsffOB4',
                'travel_dist': 6.808,
                'no_of_ratings': 5709,
                'images': ['img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/1.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/2.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/3.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/4.jpeg'],
                'cost': 10,
                'time': '8.333333333333333300951828448',
                'lat': 34.02,
                'lng': -118.29,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }
        ],
        [
            {
                'travel_time': -1,
                'rating': '4.7',
                'name': 'Griffith Park',
                'time_to_show': '9 : 00 am to 10 : 30 am',
                'place_id': 'ChIJ9590IY3AwoARquS6ie60MUc',
                'time_spent': 1.5,
                'travel_dist': -1,
                'no_of_ratings': 19078,
                'images': ['img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/1.jpeg', 'img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/2.jpeg', 'img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/3.jpeg', 'img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/4.jpeg'],
                'cost': 10,
                'time': 0,
                'lat': 34.14,
                'lng': -118.29,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 25,
                'rating': '4.5',
                'name': 'Hollywood Sign',
                'time_to_show': '10 : 55 am to 11 : 55 am',
                'place_id': 'ChIJfVpQRQq_woARQ5hwJsast6s',
                'time_spent': 1,
                'travel_dist': 12.445,
                'no_of_ratings': 3591,
                'images': ['img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/1.jpeg', 'img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/2.jpeg', 'img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/3.jpeg', 'img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/4.jpeg'],
                'cost': 10,
                'time': '1.916666666666666685170383744',
                'lat': 34.13,
                'lng': -118.32,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 17,
                'rating': '4.6',
                'name': 'Hollywood Bowl',
                'time_to_show': '12 : 12 pm to 2 : 42 pm',
                'place_id': 'ChIJMwknwRu_woAR_eI2OM9ib2o',
                'travel_dist': 5.579,
                'no_of_ratings': 6840,
                'time_spent': 2.5,
                'images': ['img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/1.jpeg', 'img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/2.jpeg', 'img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/3.jpeg', 'img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/4.jpeg'],
                'cost': 10,
                'time': '3.200000000000000011102230246',
                'lat': 34.11,
                'lng': -118.34,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 8,
                'rating': '4.7',
                'name': 'Runyon Canyon Park',
                'time_to_show': '2 : 49 pm to 3 : 49 pm',
                'place_id': 'ChIJhX1uVuC-woARQNzq4-b1Prk',
                'travel_dist': 2.346,
                'no_of_ratings': 1638,
                'time_spent': 1,
                'images': ['img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/1.jpeg', 'img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/2.jpeg', 'img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/3.jpeg', 'img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/4.jpeg'],
                'cost': 10,
                'time': '5.833333333333333342585191872',
                'lat': 34.11,
                'lng': -118.35,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 11,
                'rating': '4.7',
                'name': 'Hollywood Pantages Theatre',
                'time_to_show': '4 : 01 pm to 5 : 01 pm',
                'place_id': 'ChIJAye4Ajm_woARztbwsoUDFug',
                'travel_dist': 2.536,
                'time_spent': 1,
                'no_of_ratings': 3068,
                'images': ['img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/1.jpeg', 'img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/2.jpeg', 'img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/3.jpeg', 'img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/4.jpeg'],
                'cost': 10,
                'time': '7.016666666666666662965923251',
                'lat': 34.1,
                'lng': -118.33,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 16,
                'rating': '4.7',
                'name': 'Griffith Observatory',
                'time_to_show': '5 : 17 pm to 8 : 17 pm',
                'time_spent': 3,
                'place_id': 'ChIJywjU6WG_woAR3NrWwrEH_3M',
                'travel_dist': 6.214,
                'no_of_ratings': 3284,
                'images': ['img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/1.jpeg', 'img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/2.jpeg', 'img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/3.jpeg', 'img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/4.jpeg'],
                'cost': 10,
                'time': '8.283333333333333325931846502',
                'lat': 34.12,
                'lng': -118.3,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }
        ]
    ],
    'start_date': '2018-08-22', 
    'no_days': 2
}