laPlan = {
    'city': 'Los Angeles', 
    'tour': 
    [
        [
            {
                'travel_time': 0,
                'rating': '4.7',
                'name': 'STAPLES Center',
                'time_to_show': '9 : 00 am to 10 : 00 am',
                'time_spent': 1,
                'place_id': 'ChIJkyrqXbjHwoAR1bJ76zx89B8',
                'travel_dist': 0,
                'no_of_ratings': 9615,
                'images': ['img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/1.jpeg', 'img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/2.jpeg', 'img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/3.jpeg', 'img/data/Los Angeles/sites/ChIJkyrqXbjHwoAR1bJ76zx89B8/4.jpeg'],
                'cost': 10,
                'time': 0,
                'lat': 34.04,
                'lng': -118.27,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 10,
                'rating': '4.5',
                'name': 'El Pueblo de Los Angeles Historical Monument',
                'time_to_show': '10 : 10 am to 11 : 40 am',
                'place_id': 'ChIJgQpEAUXGwoARoG9LzK0GhV0',
                'time_spent': 1.5,
                'travel_dist': 5.202,
                'no_of_ratings': 957,
                'images': ['img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/1.jpeg', 'img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/2.jpeg', 'img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/3.jpeg', 'img/data/Los Angeles/sites/ChIJgQpEAUXGwoARoG9LzK0GhV0/4.jpeg'],
                'cost': 10,
                'time': '1.166666666666666657414808128',
                'lat': 34.06,
                'lng': -118.24,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 5,
                'rating': '4.6',
                'name': 'The Broad',
                'time_to_show': '11 : 45 am to 12 : 45 pm',
                'place_id': 'ChIJXaYsEk3GwoARvx7RKBUE8Zg',
                'time_spent': 1,
                'travel_dist': 1.637,
                'no_of_ratings': 4088,
                'images': ['img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/1.jpeg', 'img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/2.jpeg', 'img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/3.jpeg', 'img/data/Los Angeles/sites/ChIJXaYsEk3GwoARvx7RKBUE8Zg/4.jpeg'],
                'cost': 10,
                'time': '2.749999999999999986122212192',
                'lat': 34.05,
                'lng': -118.25,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 14,
                'rating': '4.7',
                'name': 'Walt Disney Concert Hall',
                'time_to_show': '4 : 08 pm to 5 : 09 pm',
                'place_id': 'ChIJ0xG7n03GwoARsDH_OyyMcrM',
                'time_spent': 1,
                'travel_dist': 7.416,
                'no_of_ratings': 3284,
                'images': ['img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/1.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/2.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/3.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/4.jpeg'],
                'cost': 10,
                'time': '7.149999999999999980571097069',
                'lat': 34.06,
                'lng': -118.25,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
                {
                'travel_time': 11,
                'rating': '4.7',
                'name': 'California Science Center',
                'time_to_show': '5 : 20 pm to 7 : 50 pm',
                'time_spent': 1.5,
                'place_id': 'ChIJ21yHTgjIwoARcrUbrsffOB4',
                'travel_dist': 6.808,
                'no_of_ratings': 5709,
                'images': ['img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/1.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/2.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/3.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/4.jpeg'],
                'cost': 10,
                'time': '8.333333333333333300951828448',
                'lat': 34.02,
                'lng': -118.29,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }
        ],
        [
            {
                'travel_time': -1,
                'rating': '4.7',
                'name': 'Griffith Park',
                'time_to_show': '9 : 00 am to 10 : 30 am',
                'place_id': 'ChIJ9590IY3AwoARquS6ie60MUc',
                'time_spent': 1.5,
                'travel_dist': -1,
                'no_of_ratings': 19078,
                'images': ['img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/1.jpeg', 'img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/2.jpeg', 'img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/3.jpeg', 'img/data/Los Angeles/sites/ChIJ9590IY3AwoARquS6ie60MUc/4.jpeg'],
                'cost': 10,
                'time': 0,
                'lat': 34.14,
                'lng': -118.29,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 25,
                'rating': '4.5',
                'name': 'Hollywood Sign',
                'time_to_show': '10 : 55 am to 11 : 55 am',
                'place_id': 'ChIJfVpQRQq_woARQ5hwJsast6s',
                'time_spent': 1,
                'travel_dist': 12.445,
                'no_of_ratings': 3591,
                'images': ['img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/1.jpeg', 'img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/2.jpeg', 'img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/3.jpeg', 'img/data/Los Angeles/sites/ChIJfVpQRQq_woARQ5hwJsast6s/4.jpeg'],
                'cost': 10,
                'time': '1.916666666666666685170383744',
                'lat': 34.13,
                'lng': -118.32,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 17,
                'rating': '4.6',
                'name': 'Hollywood Bowl',
                'time_to_show': '12 : 12 pm to 2 : 42 pm',
                'place_id': 'ChIJMwknwRu_woAR_eI2OM9ib2o',
                'travel_dist': 5.579,
                'no_of_ratings': 6840,
                'time_spent': 2.5,
                'images': ['img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/1.jpeg', 'img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/2.jpeg', 'img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/3.jpeg', 'img/data/Los Angeles/sites/ChIJMwknwRu_woAR_eI2OM9ib2o/4.jpeg'],
                'cost': 10,
                'time': '3.200000000000000011102230246',
                'lat': 34.11,
                'lng': -118.34,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 8,
                'rating': '4.7',
                'name': 'Runyon Canyon Park',
                'time_to_show': '2 : 49 pm to 3 : 49 pm',
                'place_id': 'ChIJhX1uVuC-woARQNzq4-b1Prk',
                'travel_dist': 2.346,
                'no_of_ratings': 1638,
                'time_spent': 1,
                'images': ['img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/1.jpeg', 'img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/2.jpeg', 'img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/3.jpeg', 'img/data/Los Angeles/sites/ChIJhX1uVuC-woARQNzq4-b1Prk/4.jpeg'],
                'cost': 10,
                'time': '5.833333333333333342585191872',
                'lat': 34.11,
                'lng': -118.35,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 11,
                'rating': '4.7',
                'name': 'Hollywood Pantages Theatre',
                'time_to_show': '4 : 01 pm to 5 : 01 pm',
                'place_id': 'ChIJAye4Ajm_woARztbwsoUDFug',
                'travel_dist': 2.536,
                'time_spent': 1,
                'no_of_ratings': 3068,
                'images': ['img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/1.jpeg', 'img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/2.jpeg', 'img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/3.jpeg', 'img/data/Los Angeles/sites/ChIJAye4Ajm_woARztbwsoUDFug/4.jpeg'],
                'cost': 10,
                'time': '7.016666666666666662965923251',
                'lat': 34.1,
                'lng': -118.33,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }, 
            {
                'travel_time': 16,
                'rating': '4.7',
                'name': 'Griffith Observatory',
                'time_to_show': '5 : 17 pm to 8 : 17 pm',
                'time_spent': 3,
                'place_id': 'ChIJywjU6WG_woAR3NrWwrEH_3M',
                'travel_dist': 6.214,
                'no_of_ratings': 3284,
                'images': ['img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/1.jpeg', 'img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/2.jpeg', 'img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/3.jpeg', 'img/data/Los Angeles/sites/ChIJywjU6WG_woAR3NrWwrEH_3M/4.jpeg'],
                'cost': 10,
                'time': '8.283333333333333325931846502',
                'lat': 34.12,
                'lng': -118.3,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }
        ],
        [
            {
                'travel_time': 14,
                'rating': '4.7',
                'name': 'Walt Disney Concert Hall',
                'time_to_show': '4 : 08 pm to 5 : 09 pm',
                'place_id': 'ChIJ0xG7n03GwoARsDH_OyyMcrM',
                'time_spent': 1,
                'travel_dist': 7.416,
                'no_of_ratings': 3284,
                'images': ['img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/1.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/2.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/3.jpeg', 'img/data/Los Angeles/sites/ChIJ0xG7n03GwoARsDH_OyyMcrM/4.jpeg'],
                'cost': 10,
                'time': '7.149999999999999980571097069',
                'lat': 34.06,
                'lng': -118.25,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            },
            {
                'travel_time': 11,
                'rating': '4.7',
                'name': 'California Science Center',
                'time_to_show': '5 : 20 pm to 7 : 50 pm',
                'time_spent': 1.5,
                'place_id': 'ChIJ21yHTgjIwoARcrUbrsffOB4',
                'travel_dist': 6.808,
                'no_of_ratings': 5709,
                'images': ['img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/1.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/2.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/3.jpeg', 'img/data/Los Angeles/sites/ChIJ21yHTgjIwoARcrUbrsffOB4/4.jpeg'],
                'cost': 10,
                'time': '8.333333333333333300951828448',
                'lat': 34.02,
                'lng': -118.29,
                'rating_len': [0, 1, 2, 3, 4],
                'description': ''
            }
        ]

    ],
    'start_date': '2018-08-22', 
    'no_days': 2
}

luPlan = {
	'city':  'London', 'city_description': '',  'tour': [
		[{
			'travel_time': -1,
			 'rating': '4.7',
			 'name': 'Hampton Court Palace',
			 'time_to_show': '9 : 00 am to 12 : 34 pm',
			 'place_id': 'ChIJR4IwDg4LdkgRNVpLiUw0UQ4',
			 'travel_dist': -1,
			 'no_of_ratings': 6854,
			'time_spent': 3.577777777777778,
			'images': ['img/new_data/London/sites/Hampton Court Palace/1.jpeg', 'img/new_data/London/sites/Hampton Court Palace/2.jpeg', 'img/new_data/London/sites/Hampton Court Palace/3.jpeg', 'img/new_data/London/sites/Hampton Court Palace/4.jpeg'],
			'cost': 10,
			'time': 0.0,
			'lat': 51.4,
			'lng': -0.34,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Famous seat of Henry VIII and his many wives, this palace received elegant Stuart-era modernisation.'
		}, {
			'travel_time': 42,
			'rating': '4.4',
			'name': 'River Thames',
			'time_to_show': '1 : 16 pm to 4 : 51 pm',
			'place_id': 'ChIJB4W7m_i7dkgRohLOLKSh8J0',
			'travel_dist': 47.3,
			'no_of_ratings': 853,
			'time_spent': 3.577777777777778,
			'images': ['img/new_data/London/sites/River Thames/1.jpeg', 'img/new_data/London/sites/River Thames/2.jpeg', 'img/new_data/London/sites/River Thames/3.jpeg', 'img/new_data/London/sites/River Thames/4.jpeg'],
			'cost': 10,
			'time': 4.277777777777778,
			'lat': 51.57,
			'lng': -0.61,
			'rating_len': [0, 1, 2, 3],
			'description': 'The River Thames is a river that flows through southern England, most notably through London. At 215 miles, it is the longest river entirely in England and the second longest in the United Kingdom'
		}, {
			'travel_time': 34,
			'rating': '4.6',
			'name': 'Royal Botanic Gardens, Kew',
			'time_to_show': '5 : 25 pm to 9 : 00 pm',
			'place_id': 'ChIJv9a-jNoNdkgRTd3xpTnGCdE',
			'travel_dist': 37.1,
			'no_of_ratings': 12031,
			'time_spent': 3.577777777777778,
			'images': ['img/new_data/London/sites/Royal Botanic Gardens, Kew/1.jpeg', 'img/new_data/London/sites/Royal Botanic Gardens, Kew/2.jpeg', 'img/new_data/London/sites/Royal Botanic Gardens, Kew/3.jpeg', 'img/new_data/London/sites/Royal Botanic Gardens, Kew/4.jpeg'],
			'cost': 10,
			'time': 8.422222222222222,
			'lat': 51.48,
			'lng': -0.29,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Trees and flowers from around the globe in vast gardens with huge greenhouses and Treetop Walkway.'
		}],
		[{
			'travel_time': -1,
			'rating': '4.8',
			'name': 'The Royal Albert Hall',
			'time_to_show': '9 : 00 am to 10 : 02 am',
			'place_id': 'ChIJ0XqGIVsFdkgR2S_aNe6c_l4',
			'travel_dist': -1,
			'no_of_ratings': 10526,
			'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/The Royal Albert Hall/1.jpeg', 'img/new_data/London/sites/The Royal Albert Hall/2.jpeg', 'img/new_data/London/sites/The Royal Albert Hall/3.jpeg', 'img/new_data/London/sites/The Royal Albert Hall/4.jpeg'],
			'cost': 10,
			'time': 0.0,
			'lat': 51.5,
			'lng': -0.18,
			'rating_len': [0, 1, 2, 3, 4],
			'description': "One of Britain's great Victorian splendours, most famous for the Proms classical music festival."
		}, {
			'travel_time': 24,
			'rating': '4.6',
			'name': 'Camden Market',
			'time_to_show': '10 : 26 am to 11 : 28 am',
			'place_id': 'ChIJSfFEEuQadkgRCO-FF_-eZUc',
			'travel_dist': 7.0,
			'no_of_ratings': 27408,
			'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/Camden Market/1.jpeg', 'img/new_data/London/sites/Camden Market/2.jpeg', 'img/new_data/London/sites/Camden Market/3.jpeg', 'img/new_data/London/sites/Camden Market/4.jpeg'],
			'cost': 10,
			'time': 1.4370370370370373,
			'lat': 51.54,
			'lng': -0.15,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Eclectic market with youthful vibe and stalls/shops selling fashion and accessories, music and more.'
		}, {
			'travel_time': 22,
			'rating': '4.6',
			'name': 'Trafalgar Square',
			'time_to_show': '11 : 50 am to 12 : 52 pm',
			'place_id': 'ChIJH-tBOc4EdkgRJ8aJ8P1CUxo',
			'travel_dist': 5.2,
			'no_of_ratings': 33848,
			'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/Trafalgar Square/1.jpeg', 'img/new_data/London/sites/Trafalgar Square/2.jpeg', 'img/new_data/London/sites/Trafalgar Square/3.jpeg', 'img/new_data/London/sites/Trafalgar Square/4.jpeg'],
			'cost': 10,
			'time': 2.840740740740741,
			'lat': 51.51,
			'lng': -0.13,
			'rating_len': [0, 1, 2, 3, 4],
			'description': "Nelson's Column rises above this iconic square's LED-lit fountains, artworks and lion statues."
		}, {
			'travel_time': 16,
			'rating': '4.6',
			'name': 'Hyde Park',
			'time_to_show': '1 : 08 pm to 2 : 10 pm',
			'place_id': 'ChIJhRoYKUkFdkgRDL20SU9sr9E',
			'travel_dist': 4.9,
			'no_of_ratings': 35123,
			'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/Hyde Park/1.jpeg', 'img/new_data/London/sites/Hyde Park/2.jpeg', 'img/new_data/London/sites/Hyde Park/3.jpeg', 'img/new_data/London/sites/Hyde Park/4.jpeg'],
			'cost': 10,
			'time': 4.144444444444445,
			'lat': 51.51,
			'lng': -0.17,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Huge green space, home to Diana Memorial Fountain, with boating and swimming in the Serpentine lake.'
		}, {
			'travel_time': 7,
			'rating': '4.7',
			'name': 'Natural History Museum, London',
			'time_to_show': '2 : 17 pm to 3 : 20 pm',
			'place_id': 'ChIJPy8Y5kIFdkgRxGSXw4Xjt3s',
			'travel_dist': 1.9,
			'no_of_ratings': 7154,
			'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/Natural History Museum, London/1.jpeg', 'img/new_data/London/sites/Natural History Museum, London/2.jpeg', 'img/new_data/London/sites/Natural History Museum, London/3.jpeg', 'img/new_data/London/sites/Natural History Museum, London/4.jpeg'],
			'cost': 10,
			'time': 5.298148148148149,
			'lat': 51.5,
			'lng': -0.18,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Landmark museum of animals and natural phenomena, with hands-on exhibits and animatronic dinosaurs.'
		}, {
			'travel_time': 13,
			'rating': '4.7',
			'name': "St James's Park",
			'time_to_show': '3 : 33 pm to 4 : 35 pm',
			'place_id': 'ChIJG-CxwNoEdkgRXx26gHZwVf8',
			'travel_dist': 3.7,
			'no_of_ratings': 12076,
			'time_spent': 1.0370370370370372,
			'images': ["img/new_data/London/sites/St James's Park/1.jpeg", "img/new_data/London/sites/St James's Park/2.jpeg", "img/new_data/London/sites/St James's Park/3.jpeg", "img/new_data/London/sites/St James's Park/4.jpeg"],
			'cost': 10,
			'time': 6.551851851851851,
			'lat': 51.5,
			'lng': -0.13,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Green space with a lake with daily pelican feeding, a grass-roofed cafe and ceremonial displays.'
		}, {
			'travel_time': 11,
			'rating': '4.7',
			'name': 'Victoria and Albert Museum',
			'time_to_show': '4 : 46 pm to 5 : 48 pm',
			'place_id': 'ChIJw1d-sUMFdkgRH2XN_U0Jt54',
			'travel_dist': 3.4,
			'no_of_ratings': 17275,
			'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/Victoria and Albert Museum/1.jpeg', 'img/new_data/London/sites/Victoria and Albert Museum/2.jpeg', 'img/new_data/London/sites/Victoria and Albert Museum/3.jpeg', 'img/new_data/London/sites/Victoria and Albert Museum/4.jpeg'],
			'cost': 10,
			'time': 7.772222222222222,
			'lat': 51.5,
			'lng': -0.17,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Blockbuster exhibitions and permanent decorative arts collection, with design shop and ornate cafe.'
		}, {
			'travel_time': 32,
			'rating': '4.7',
			'name': 'Tower Bridge',
			'time_to_show': '6 : 20 pm to 7 : 22 pm',
			'place_id': 'ChIJSdtli0MDdkgRLW9aCBpCeJ4',
			'travel_dist': 8.6,
			'no_of_ratings': 38248,
			'time_spent': 1.0370370370370372,
			 'images': ['img/new_data/London/sites/Tower Bridge/1.jpeg', 'img/new_data/London/sites/Tower Bridge/2.jpeg', 'img/new_data/London/sites/Tower Bridge/3.jpeg', 'img/new_data/London/sites/Tower Bridge/4.jpeg'],
			 'cost': 10,
			 'time': 9.342592592592593,
			 'lat': 51.51,
			 'lng': -0.08,
			 'rating_len': [0, 1, 2, 3, 4],
			 'description': 'Panoramic views from high level walkways and behind-the-scenes access to original lifting machinery.'
		}, {
			 'travel_time': 21,
			 'rating': '4.7',
			 'name': 'British Museum',
			 'time_to_show': '7 : 43 pm to 8 : 46 pm',
			 'place_id': 'ChIJB9OTMDIbdkgRp0JWbQGZsS8',
			 'travel_dist': 6.2,
			 'no_of_ratings': 45824,
			 'time_spent': 1.0370370370370372,
			'images': ['img/new_data/London/sites/British Museum/1.jpeg', 'img/new_data/London/sites/British Museum/2.jpeg', 'img/new_data/London/sites/British Museum/3.jpeg', 'img/new_data/London/sites/British Museum/4.jpeg'],
			'cost': 10,
			'time': 10.729629629629631,
			'lat': 51.52,
			'lng': -0.13,
			'rating_len': [0, 1, 2, 3, 4],
			'description': 'Huge showcase for global antiquities, including Egyptian mummies and ancient Greek sculptures.'
		}]
	], 'city_image': 'img/new_data/London/London.jpg', 'start_date': '2018-08-23', 'no_days': 2
}
