# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.15 on 2018-08-18 17:07
=======
# Generated by Django 1.11.15 on 2018-08-17 06:34
>>>>>>> 52087ba3a25cfb975614f20b99ebf3e1a85d712a
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40)),
<<<<<<< HEAD
=======
                ('city_uuid', models.UUIDField()),
>>>>>>> 52087ba3a25cfb975614f20b99ebf3e1a85d712a
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.City')),
            ],
        ),
        migrations.CreateModel(
            name='OpenCloseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.IntegerField()),
                ('close_time', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.TextField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('photo_src', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POI_id', models.TextField()),
                ('POI_image_src', models.URLField()),
                ('POI_name', models.CharField(max_length=40)),
                ('formatted_address', models.TextField()),
                ('formatted_phoneNo', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('POI_map_url', models.URLField()),
                ('POI_website_url', models.URLField()),
<<<<<<< HEAD
                ('average_time_spent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('POI_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.City', verbose_name='point of interest of the corresponding city')),
=======
                ('POI_city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.City', verbose_name='point of interest of the corresponding city')),
>>>>>>> 52087ba3a25cfb975614f20b99ebf3e1a85d712a
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='types',
<<<<<<< HEAD
            field=models.ManyToManyField(blank=True, null=True, to='iteneraryApplication.Type'),
=======
            field=models.ManyToManyField(to='iteneraryApplication.Type'),
>>>>>>> 52087ba3a25cfb975614f20b99ebf3e1a85d712a
        ),
        migrations.AddField(
            model_name='photo',
            name='POI',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.PointOfInterest', verbose_name='photo of corresponding point of interest'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.PointOfInterest', verbose_name='photo of corresponding point of interest'),
>>>>>>> 52087ba3a25cfb975614f20b99ebf3e1a85d712a
        ),
        migrations.AddField(
            model_name='openclosetime',
            name='POI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.PointOfInterest', verbose_name='the opening and closing time of the corresponding point of interest on a certain day'),
        ),
        migrations.AddField(
            model_name='form',
            name='type_tags',
<<<<<<< HEAD
            field=models.ManyToManyField(blank=True, null=True, to='iteneraryApplication.Type'),
=======
            field=models.ManyToManyField(to='iteneraryApplication.Type'),
>>>>>>> 52087ba3a25cfb975614f20b99ebf3e1a85d712a
        ),
    ]
