# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteneraryApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
