# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteneraryApplication', '0002_remove_city_city_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type_tags',
            field=models.ManyToManyField(blank=True, null=True, to='iteneraryApplication.Type'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='POI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.PointOfInterest', verbose_name='photo of corresponding point of interest'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='POI_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iteneraryApplication.City', verbose_name='point of interest of the corresponding city'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='iteneraryApplication.Type'),
        ),
    ]
