# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteneraryApplication', '0002_auto_20180819_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='id',
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
