# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteneraryApplication', '0003_auto_20180819_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
